# Generated by Django 5.0.7 on 2024-08-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("usuario_id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("data", models.DateField()),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="app_1.usuario",
                    ),
                ),
            ],
        ),
    ]
